---
title: "6260 Project"
author: "Emily Wu"
date: "2026-04-15"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(knitr)
```

```{r, pathway 2 EDA}
#load("37692-0002-Data.rda")
data<-da37692.0002
#1185-1191 for Disorders

v_range <- function(start, end) {
  sprintf("V%04d", as.numeric(start):as.numeric(end))}
MHD<-v_range("1185", "1191")

sblist <- data %>%
  select(all_of(MHD))
sblist<-sblist%>%
  mutate(across(all_of(MHD), ~ as.numeric(gsub(".*\\((-?\\d+)\\).*", "\\1", as.character(.x)))))
sblist



sblist <- sblist %>%
  rename("Bipolar" = V1185)%>%
  rename("Depression" = V1186)%>%
  rename("Schizophrenia" = V1187)%>%
  rename("PTSD" = V1188)%>%
  rename("Anxiety" = V1189)%>%
  rename("Personality Disorder" = V1190)%>%
  rename("Other Diagnosis" = V1191)
tables_df <- apply(MARGIN = 2, sblist, FUN = table)
vect<-tables_df[3,]/nrow(data)
tables_df<-rbind(tables_df, vect)

```


```{r, pathway 3 eda}
#proposed variables
varlist<-c("V0411", "V0413","V0414","V0415","V0935", "V0944", "V0945", "V0982", "V1166", "V1165", "V1167", "V1168", "V1264", "V1252")
varlist<- c(varlist, v_range("1170", "1174"))

sblist<- data%>%
  select(all_of(varlist))



sblist <- sblist %>%
  rename("Years of Education" = V0935) %>%
  rename("Total Max Sentence" = V0411) %>%
  rename("Max Sentence # of Years" = V0413) %>%
  rename("Max Sentence # of Months" = V0414) %>%
  rename("Max Sentence # of Days" = V0415) %>%
  rename("SpEd" = V0944) %>%
  rename("Born in the US" = V0945) %>%
  rename("Children" = V0982)%>%
  rename("Foster Home" = V1166)%>%
  rename("Homeless" = V1165)%>%
  rename("Specify Home or Institution" = V1167)%>%
  rename("Lived with most time" = V1168) %>%
  rename("Welfare" = V1170) %>%
  rename("Public Housing" = V1171) %>%
  rename("Father" = V1172) %>%
  rename("Mother" = V1173) %>%
  rename("Sibling" = V1174) 
  

 .

  
  
  
  
  
  




```

